- name: install and run nginx
  hosts: web
  become: yes # -b as sudo access
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present #present is for install and absent is for remove
    - name: start the nginx
      ansible.builtin.service:
        name: nginx
        state: started
