- name: variable prompt
  hosts: local
  connection: local
  vars_prompt:
    - name: Course
      prompt: please enter course name
      private: false # it is not confidential, the text is visible in prompt
    - name: Duration
      prompt: Please enter the duration
      private: false # it is not confidential, the text is visible in prompt
    - name: Trainer
      prompt: "Please enter the duration"
      private: false # it is not confidential, the text is visible in prompt
  tasks:
    - name: variables from prompt
      ansible.builtin.debug:
        msg: "Course is {{Course}} and duration is {{Duration}}, trainer was {{Trainer}}"
