- name: variables from args
  hosts: local
  tasks:
    - name: variable from arg
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
