- name: variables
  hosts: local
  connection: local
  # vars:
  #   GREET: "PLAY"
  # vars_files:
  #   - vars.yaml
  # vars_prompt:
  #   - name: GREET
  #     prompt: Enter the value
  #     private: false
  tasks:
    - name: print the variables
      # vars:
      #   GREET: "TASK"
      ansible.builtin.debug:
        msg: "Hello from {{GREET}}"
#1. Args will print in command line
#2. second local variables will print
#3. var.yaml file variables will print
#4. var prompt variables will print
#5. PLAY or Global variables will print
#6. from inventory

