- name: check if number is greater than 10 or not
  hosts: local
  connection: local
  vars:
    number: 15
  tasks:
    - name: given number is greater than 10
      ansible.builtin.debug:
        msg: "Given number {{number}} is greater than 10"
      when: number > 10

    - name: given number is less than or equalto 10
      ansible.builtin.debug:
        msg: "Given number {{number}} is less than 10"
      when: number <= 10
