- name: install and uninstall the packages
  hosts: web
  become: yes
  tasks: 
  - name: install and uninstall the softwares
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name: "nginx", state: "absent"}
    - { name: "mysql", state: "present"}
    - { name: "git", state: "present"}