- name: filters or functions
  hosts: local
  connection: local
  tasks:
    - name: filters or functions
      ansible.builtin.debug:
        msg: "Hello {{ person | default('Ajay') }}"
    - name: converting string to list
      vars:
        fruits: "apple, mango, orange"
      ansible.builtin.debug:
        msg: "Fruits are: {{fruits | split(',')}}"

    - name: converting map into list
      vars:
        course:
          name: ansible
          duration: 10hrs
          trainer: siva
      ansible.builtin.debug:
        msg: " course info: {{ course | dict2items }}"

    - name: convert list into map
      vars:
        course:
          - { "key": "name", "value": "ansible" }
          - { "key": "Duration", "value": "10HRS" }
          - { "key": "TRAINER", "value": "SIVA" }
      ansible.builtin.debug:
        msg: "Course info: {{ course | items2dict }}"

    - name: convert upper to lower
      vars:
        name: "Ajay kumar reddy"
      ansible.builtin.debug:
        msg: "Hello {{ name | lower }}"
